server:
  port: 8080

spring:
  application:
    name: shin

  data:
    mongodb:
      username: shin-dev
      password: shin-dev
      port: 27017
      host: localhost
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/
      database: shin

  security:
    user:
      password: shin-dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}
    status-page-url: http://${eureka.hostname}
    healthCheckUrl: http://${eureka.hostname}/actuator/health
    secureHealthCheckUrl: http://${eureka.hostname}/actuator/health